<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ActivityExplorer.Core\ActivityExplorer.Core.csproj" />
    <ProjectReference Include="..\ActivityExplorer.Data\ActivityExplorer.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.SDK" Version="7.4.0" />
    <PackageReference Include="System.Management.Automation" Version="7.4.0" />
    <PackageReference Include="Microsoft.WSMan.Management" Version="7.4.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.74.1" />
    <PackageReference Include="Azure.Identity" Version="1.11.4" />
    <PackageReference Include="Azure.Core" Version="1.39.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.14.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.14.0" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="8.14.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols" Version="8.14.0" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.14.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

</Project>
